name: 'Release'
on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      packages: write
    # See https://github.com/Kotori316/common-script/blob/main/.github/workflows/release-prod-gradle.yaml
    uses: 'Kotori316/common-script/.github/workflows/release-prod-gradle.yaml@main'
    with:
      sign_check_command: 'assemble publishToMavenLocal'
      release_command: 'checkReleaseVersion assemble publishToMavenLocal publishMods registerVersion publish'
      enable_signature_check: true
    secrets: inherit
